# Generated by Django 4.2.2 on 2023-06-14 14:47

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wallet_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to=api.models.image_uoload_profile)),
            ],
        ),
        migrations.CreateModel(
            name='MarquePrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.image_uoload_profile),
        ),
        migrations.AddField(
            model_name='vendor',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.image_uoload_profile),
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.IntegerField(default=1, max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to=api.models.image_uoload)),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categorie')),
                ('fournisseurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.manager')),
                ('marqueprives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.marqueprive')),
            ],
        ),
    ]
