# Generated by Django 4.2.2 on 2023-06-14 18:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_categorie_marqueprive_manager_image_vendor_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='fournisseurs',
            new_name='manager',
        ),
        migrations.AlterField(
            model_name='manager',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.image_uoload_profile),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.image_uoload_profile),
        ),
    ]
