# Generated by Django 4.2.2 on 2023-06-14 19:04

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_fournisseurs_produit_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.image_uoload_profile),
        ),
        migrations.AlterField(
            model_name='produit',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.image_uoload_profile),
        ),
    ]
